name: mal_learn
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  file_picker: ^4.5.1
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_riverpod: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
