name: mal_learn
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  file_picker: ^4.5.1
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_markdown: ^0.6.9
  flutter_riverpod: ^1.0.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: any

flutter:
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/terms.md
